# Generated by Django 6.0.4 on 2026-04-08 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Máquina')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('precio_por_dia', models.IntegerField(verbose_name='Precio por Día')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Término')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Confirmación'), ('aprobado', 'Aprobado y Pagado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendos', to='arriendos.maquina')),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
            },
        ),
    ]
