# Generated by Django 6.0.4 on 2026-04-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='email_cliente',
            field=models.EmailField(default='sin@correo.com', max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='nombre_cliente',
            field=models.CharField(default='Cliente Antiguo', max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='telefono_cliente',
            field=models.CharField(default='+56900000000', max_length=20, verbose_name='Teléfono'),
        ),
    ]
